### ISSUE TITLE
UPDATE?!

### ISSUE THREAD

**Issue by ghostt187** [NiGHT757/SlayLosers#1]
will there ba any update for this plugin?
1. able to edit the message in a config file
2. upgrade to 8.0

**Comment by NiGHT757** [comment]
Added [v0.0.2](https://github.com/NiGHT757/SlayLosers/releases/tag/v0.0.2)

**Comment by ghostt187** [comment]
is it updated to net8.0?

**Comment by NiGHT757** [comment]
> is it updated to net8.0?

Yes
